### ISSUE TITLE
Auto-play removed?

### ISSUE THREAD

**Issue by dkleissa** [rubentd/gifplayer#9]
The version of the library on the demo site (http://rubentd.com/gifplayer/) is different than master.  It has auto-play capability, but that seems to be removed now?  Was this for a reason?

**Comment by rubentd** [comment]
HI, I removed it because it didn't work properly in some cases. If you need this feature, you can still implement it, creating a js code that detects when the gif is in the visible viewport (http://stackoverflow.com/questions/123999/how-to-tell-if-a-dom-element-is-visible-in-the-current-viewport), 
and then trigger the play method: For example $('#banana').gifplayer('play');
